<?php

/**
 * This is the model base class for the table "{{spray}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Spray".
 *
 * Columns in table "{{spray}}" available as properties of the model,
 * followed by relations of table "{{spray}}" available as properties of the model.
 *
 * @property string $id
 * @property string $chemical_id
 * @property string $date
 * @property integer $quantity
 * @property integer $block_id
 * @property string $creator_id
 * @property integer $ordering
 * @property string $created_at
 * @property string $updated_at
 * @property integer $status
 * @property integer $is_deleted
 * @property string $params
 *
 * @property Block $block
 * @property Chemical $chemical
 */
abstract class BaseSpray extends SimbActiveRecord{
    public static function model($className=__CLASS__)
    {
		return parent::model($className);
	}

	public function tableName()
    {
		return '{{spray}}';
	}

	public static function representingColumn()
    {
		return 'date';
	}

	public function rules()
    {
		return array(
			array('chemical_id, date, quantity, block_id', 'required'),
			array('quantity, block_id, ordering, status, is_deleted', 'numerical', 'integerOnly'=>true),
			array('chemical_id', 'length', 'max'=>10),
			array('creator_id', 'length', 'max'=>20),
			array('created_at, updated_at, params', 'safe'),
			array('creator_id, ordering, created_at, updated_at, status, is_deleted, params', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, chemical_id, date, quantity, block_id, creator_id, ordering, created_at, updated_at, status, is_deleted, params, rowsPerPage', 'safe', 'on'=>'search'),
		);
	}

	public function relations()
    {
		return array(
			'block' => array(self::BELONGS_TO, 'Block', 'block_id'),
			'chemical' => array(self::BELONGS_TO, 'Chemical', 'chemical_id'),
		);
	}

	public function pivotModels()
    {
		return array(
		);
	}

	public function attributeLabels()
    {
		return array(
			'id' => Yii::t('app', 'ID'),
			'chemical_id' => Yii::t('app', 'Chemical'),
			'date' => Yii::t('app', 'Date'),
			'quantity' => Yii::t('app', 'Quantity'),
			'block_id' => Yii::t('app', 'Block'),
			'creator_id' => Yii::t('app', 'Creator'),
			'ordering' => Yii::t('app', 'Ordering'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'params' => Yii::t('app', 'Params'),
		);
	}

	public function search()
    {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('chemical_id', $this->chemical_id);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('quantity', $this->quantity);
		$criteria->compare('block_id', $this->block_id);
		$criteria->compare('creator_id', $this->creator_id, true);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('params', $this->params, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => $this->rowsPerPage,
			)
		));
	}
}