<?php

/**
 * This is the model base class for the table "{{property}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Property".
 *
 * Columns in table "{{property}}" available as properties of the model,
 * followed by relations of table "{{property}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $grower_id
 * @property string $location_id
 * @property string $name
 * @property string $creator_id
 * @property integer $ordering
 * @property string $created_at
 * @property string $updated_at
 * @property integer $status
 * @property integer $is_deleted
 * @property string $params
 *
 * @property Block[] $blocks
 * @property Location $location
 * @property Grower $grower
 */
abstract class BaseProperty extends SimbActiveRecord{
    public static function model($className=__CLASS__)
    {
		return parent::model($className);
	}

	public function tableName()
    {
		return '{{property}}';
	}

	public static function representingColumn()
    {
		return 'location_id';
	}

	public function rules()
    {
		return array(
			array('grower_id, location_id', 'required'),
			array('grower_id, ordering, status, is_deleted', 'numerical', 'integerOnly'=>true),
			array('location_id, name', 'length', 'max'=>100),
			array('creator_id', 'length', 'max'=>20),
			array('created_at, updated_at, params', 'safe'),
			array('name, creator_id, ordering, created_at, updated_at, status, is_deleted, params', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, grower_id, location_id, name, creator_id, ordering, created_at, updated_at, status, is_deleted, params, rowsPerPage', 'safe', 'on'=>'search'),
		);
	}

	public function relations()
    {
		return array(
			'blocks' => array(self::HAS_MANY, 'Block', 'property_id'),
			'location' => array(self::BELONGS_TO, 'Location', 'location_id'),
			'grower' => array(self::BELONGS_TO, 'Grower', 'grower_id'),
		);
	}

	public function pivotModels()
    {
		return array(
		);
	}

	public function attributeLabels()
    {
		return array(
			'id' => Yii::t('app', 'ID'),
			'grower_id' => Yii::t('app', 'Grower'),
			'location_id' => Yii::t('app', 'Location'),
			'name' => Yii::t('app', 'Property'),
			'creator_id' => Yii::t('app', 'Creator'),
			'ordering' => Yii::t('app', 'Ordering'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'params' => Yii::t('app', 'Params'),
		);
	}

	public function search()
    {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('grower_id', $this->grower_id);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('creator_id', $this->creator_id, true);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('params', $this->params, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => $this->rowsPerPage,
			)
		));
	}
}