<?php

/**
 * This is the model base class for the table "{{mite_monitor}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MiteMonitor".
 *
 * Columns in table "{{mite_monitor}}" available as properties of the model,
 * followed by relations of table "{{mite_monitor}}" available as properties of the model.
 *
 * @property string $id
 * @property integer $mite_id
 * @property integer $block_id
 * @property string $creator_id
 * @property double $percent_li
 * @property double $average_li
 * @property string $date
 * @property double $no_days
 * @property integer $ordering
 * @property string $created_at
 * @property string $updated_at
 * @property integer $status
 * @property integer $is_deleted
 * @property string $params
 *
 * @property Block $block
 * @property Mite $mite
 */
abstract class BaseMiteMonitor extends SimbActiveRecord{
	
    public static function model($className=__CLASS__)
    {
		return parent::model($className);
	}

	public function tableName()
    {
		return '{{mite_monitor}}';
	}

	public static function representingColumn()
    {
		return 'created_at';
	}

	public function rules()
    {
		return array(
			array('mite_id, block_id, date, percent_li, average_li', 'required','except' => 'search'),
			array('mite_id, block_id, ordering, status, is_deleted', 'numerical', 'integerOnly'=>true),
			array('percent_li, average_li, no_days', 'numerical'),
			array('creator_id', 'length', 'max'=>20),
			array('created_at, updated_at, params', 'safe'),
			array('percent_li, average_li, no_days, creator_id, ordering, created_at, updated_at, status, is_deleted, params', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, mite_id, block, property, mite, grower, block_id, date, percent_li, average_li, no_days, creator_id, ordering, created_at, updated_at, status, is_deleted, params, rowsPerPage', 'safe', 'on'=>'search'),
		);
	}

	public function relations()
    {
		return array(
			'block' => array(self::BELONGS_TO, 'Block', 'block_id'),
			'mite' => array(self::BELONGS_TO, 'Mite', 'mite_id'),
		);
	}

	public function pivotModels()
    {
		return array(
		);
	}

	public function attributeLabels()
    {
		return array(
			'id' => Yii::t('app', 'ID'),
			'mite_id' => Yii::t('app', 'Mite'),
			'block_id' => Yii::t('app', 'Block'),
			'date' => Yii::t('app', 'Date'),
			'percent_li' => Yii::t('app', 'Percent Li'),
			'average_li' => Yii::t('app', 'Average Li'),
			'no_days' => Yii::t('app', 'No days'),
			'creator_id' => Yii::t('app', 'Creator'),
			'ordering' => Yii::t('app', 'Ordering'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'params' => Yii::t('app', 'Params'),
		);
	}

	public function search()
    {
		$criteria = new CDbCriteria;
		
		$criteria->with=array('block','property','grower');
		
		$criteria->compare('id', $this->id, true);
		$criteria->compare('mite_id', $this->mite_id);
		$criteria->compare('block_id', $this->block_id);
		$criteria->compare('property.id', $this->property);
		$criteria->compare('grower.id', $this->grower);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('percent_li', $this->percent_li);
		$criteria->compare('average_li', $this->average_li);
		$criteria->compare('no_days', $this->no_days, true);
		$criteria->compare('creator_id', $this->creator_id, true);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('params', $this->params, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => $this->rowsPerPage,
			)
		));
	}
}