<?php

/**
 * This is the model base class for the table "{{sizing}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sizing".
 *
 * Columns in table "{{sizing}}" available as properties of the model,
 * followed by relations of table "{{sizing}}" available as properties of the model.
 *
 * @property string $id
 * @property integer $block_id
 * @property string $variety_id
 * @property string $date
 * @property double $value
 * @property string $type
 * @property string $creator_id
 * @property integer $ordering
 * @property string $created_at
 * @property string $updated_at
 * @property integer $status
 * @property integer $is_deleted
 * @property string $params
 *
 * @property Variety $variety
 * @property Block $block
 */
abstract class BaseSizing extends SimbActiveRecord{
    public static function model($className=__CLASS__)
    {
		return parent::model($className);
	}

	public function tableName()
    {
		return '{{sizing}}';
	}

	public static function representingColumn()
    {
		return 'date';
	}

	public function rules()
    {
		return array(
			array('block_id, variety_id, date, value, type', 'required'),
			array('block_id, ordering, status, is_deleted', 'numerical', 'integerOnly'=>true),
			array('value', 'numerical'),
			array('variety_id', 'length', 'max'=>10),
			array('type', 'length', 'max'=>6),
			array('creator_id', 'length', 'max'=>20),
			array('created_at, updated_at, params', 'safe'),
			array('creator_id, ordering, created_at, updated_at, status, is_deleted, params', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, block_id, variety_id, date, value, type, creator_id, ordering, created_at, updated_at, status, is_deleted, params, rowsPerPage', 'safe', 'on'=>'search'),
		);
	}

	public function relations()
    {
		return array(
			'variety' => array(self::BELONGS_TO, 'Variety', 'variety_id'),
			'block' => array(self::BELONGS_TO, 'Block', 'block_id'),
		);
	}

	public function pivotModels()
    {
		return array(
		);
	}

	public function attributeLabels()
    {
		return array(
			'id' => Yii::t('app', 'ID'),
			'block_id' => Yii::t('app', 'Block'),
			'block.name' => Yii::t('app', 'Block'),
			'variety_id' => Yii::t('app', 'Variety'),
			'variety.name' => Yii::t('app', 'Variety'),
			'date' => Yii::t('app', 'Date'),
			'value' => Yii::t('app', 'Value'),
			'type' => Yii::t('app', 'Type'),
			'creator_id' => Yii::t('app', 'Creator'),
			'ordering' => Yii::t('app', 'Ordering'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'params' => Yii::t('app', 'Params'),
		);
	}

	public function search()
    {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('block_id', $this->block_id);
		$criteria->compare('variety_id', $this->variety_id);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('value', $this->value);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('creator_id', $this->creator_id, true);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('params', $this->params, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => $this->rowsPerPage,
			)
		));
	}
}