<?php
/**
 * Yii configurations for FrontEnd
 */
return array(
    'name' => 'Fruit Growers Victoria',
    'basePath' => dirname(__FILE__) . DS . '..' . DS . '..',
    'theme' => 'default',
    // path aliases
    'aliases' => array(
        // change this if necessary
        'bootstrap' => realpath(__DIR__ . DS . '..' . DS . '..' . DS . 'extensions' . DS . 'bootstrap'),
    ),
    // autoloading model and component classes
    'import' => array(
        'application.extensions.giix-components.*',
        'application.models.frontend.*',
        'application.models.service.*',
        'application.components.*',
        // For bootstrap
        'bootstrap.helpers.*',
        'bootstrap.widgets.*',
        'bootstrap.behaviors.*',
    ),
    'preload' => array(
        'log',
    ),
    'behaviors' => array(
        // separate frontend and backend
        'runEnd' => array(
            'class' => 'application.components.SimbWebApplicationEndBehavior',
        ),
    ),
    'modules' => array(
        // uncomment the following to enable the Gii tool
        'gii' => array(
            'class' => 'system.gii.GiiModule',
            'generatorPaths' => array(
                'bootstrap.gii', // since 0.9.1
                'ext.giix-core', // giix generators
                'application.gii',

            ),
            'password' => '123456',
            // If removed, Gii defaults to localhost only. Edit carefully to taste.
            'ipFilters' => array('127.0.0.1', '::1'),
        ),
    ),
    'components' => CMap::mergeArray(
            require(dirname(__FILE__) . DS . '..' . DS . 'db_connect.php'),
            array(
                // Asset management
                'assetManager' => array(
                    // Set the path for the assets generated by Yii
                    'basePath' => dirname(__FILE__) . DS . '..' . DS . '..' . DS . '..' . DS . 'assets',
                    // Set the base Url, should be changed on local machine
                    'baseUrl' => '/assets',
                ),
                // Logging system
                'log' => array(
                    'class' => 'CLogRouter',
                    'routes' => array(
                        array(
                            'class' => 'CFileLogRoute',
                            'levels' => 'error, warning, info, trace',
                            'maxFileSize' => 16384, // 16mb
                            'maxLogFiles' => 99,
                        ),
                        // debug toolbar configuration
                        array(
                            'class' => 'application.extensions.debugtoolbar.XWebDebugRouter',
                            'config' => 'alignLeft, opaque, runInDebug, fixedPos, collapsed, yamlStyle',
                            'levels' => 'error, warning, info, trace',
                            'allowedIPs' => array('127.0.0.1', $_SERVER['REMOTE_ADDR']),
                        ),
                        array(
                            'class' => 'ext.db_profiler.DbProfileLogRoute',
                            'countLimit' => 1,
                            // How many times the same query should be executed to be considered inefficient
                            'slowQueryMin' => 1.00,
                            // Minimum time for the query to be slow
                        ),
                    ),
                ),
                // ClientScript
                'clientScript' => array(
                    'class' => 'ext.npMinScript.NpMinScript',
                    'combineScriptFiles' => false,
                    // By default this is set to true, change it to false to disable combining JS files
                    'combineCssFiles' => false,
                    // By default this is set to true, change it to false to disable combining CSS files
                    'optimizeScriptFiles' => false,
                    // @since: 1.1
                    'optimizeCssFiles' => false,
                    // @since: 1.1
                    'maxFileSize' => 200000,
                    'cacheObjectName' => 'fileCache',
                    'cacheTimeout' => 10800,
                    'jsPosEnd' => true,
                ),
                'fileCache' => array(
                    'class' => 'CFileCache'
                ),
                // Init bootstrap
                'bootstrap' => array(
                    'class' => 'bootstrap.components.TbApi',

                ),
                // Use session of the browser
                'session' => array(
                    'class' => 'CHttpSession',
                ),
                // Handling user session
                'user' => array(
                    'class' => 'application.components.SimbWebUser',
                    'loginUrl' => array('site/login'),
                    // Handling cleaning flashes automatically
                    'autoUpdateFlash' => false,
                    // enable cookie-based authentication
                    'allowAutoLogin'=>true,
	   
                ),
                // Url Manager
                'urlManager' => array(
                    'class' => 'SimbUrlManagerFrontend',
                    'urlFormat' => 'path',
                    'rules' => require(dirname(__FILE__) . DS . 'routes.php'),
                    'showScriptName' => false,
                    'appendParams' => false,
                ),
            )
        ),
    // array of params for the whole app
    'params' => CMap::mergeArray(
            require(dirname(__FILE__) . DS . '..' . DS . 'params.php'),
            // Extra params
            array()
        ),
);